version: '3.8'
services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: FelipeSilva
      POSTGRES_PASSWORD: FFbs@@2024
      POSTGRES_DB: yourdatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: yourdatabase
      DB_USER: FelipeSilva
      DB_PASSWORD: FFbs@@2024
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    ports:
      - "3000:3000"

volumes:
  postgres_data:
